name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        # actions/checkout@v4

      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac
        # jdx/mise-action@v2

      - name: Run tests
        run: mise run test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        # actions/checkout@v4

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff
        # actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84
        # golangci/golangci-lint-action@v6
        with:
          version: v1.64.0
          args: --timeout=5m
